<?php

return new \Phalcon\Config(array(
    'siteCfg'	=> array(
        'title'  	=> '慧学网',
        'subTitle'  => '您的理财知识库',
        'logoFile' 	=> APP_PATH . '/public/img/logo.png',
    ),
    'cacheCfg' 	=> array(
        'expireTime' => 3600,
    ),
    'footerCft'	=> array(
    	'cright'	=> 'CopyRight © 2014 <a target="_blank" href="http://www.miitbeian.gov.cn/">鲁ICP备14026710号-1</a> 慧学屋',
    	'contentFrom'	=> '本站资源多收集于网络,版权归原作者所有,若有侵权,请联系我们. admin@licaimap.com',
    	'tips'		=> '声明：本站发布的所有资料或图片仅仅用于学习与交流，投资者依据本网站提供的内容进行投资所造成的盈亏与本网站无关。',
    ),
    'nodeCfg'	=> array(
		'menuRootNid' => 6975,
        'mainMenuRootNid' => 2,
        'secMenuRootNid' => 6977,
        'recommendNodeNum' => 6,
        'articleRootNid' => 2,
        'hotNids' => '',
        'homeSliderNids' => '',
        'xtSliderNids' => '',
    ),
    'widgetCfg'	=> array(
    	'cidianCloudNum' => 30,
        'tagNodesNum' => 20,
        'listItemPer' => 20,
        'blockNum' => 6,
    ),
    'slider' => array(
		'home' => array(
			array('title'=>'', 'img_path'=>'', 'link'=>'', 'alt'=>''),
			array('title'=>'', 'img_path'=>'', 'link'=>'', 'alt'=>''),
			array('title'=>'', 'img_path'=>'', 'link'=>'', 'alt'=>''),
		),
		'school' => array(
			array('title'=>'', 'img_path'=>'', 'link'=>'', 'alt'=>''),
			array('title'=>'', 'img_path'=>'', 'link'=>'', 'alt'=>''),
			array('title'=>'', 'img_path'=>'', 'link'=>'', 'alt'=>''),
			array('title'=>'', 'img_path'=>'', 'link'=>'', 'alt'=>''),
		),
	),
    'blockCfg'	=> array(
    	'slider_home' => array(array('nid' => 29,'title' => '投资案例')),
        'slider_school' => array(array('nid' => 9,'title' => '财经学堂')),
        'navTab_school_stock_fund' => array(array('nid' => 17,'title' => '股票学堂'),array('nid' => 18,'title' => '基金学堂')),
        'navTab_school_forex_bank' => array(array('nid' => 19,'title' => '外汇学堂'),array('nid' => 20,'title' => '银行学堂')),
        'navTab_school_spot_futures' => array(array('nid' => 22,'title' => '现货学堂'),array('nid' => 23,'title' => '期货学堂')),
        'panel_internet_licai' => array(array('nid' => 13,'title' => '互联网理财')),
        'panel_internet_p2p' => array(array('nid' => 14,'title' => 'p2p网贷')),
        'navTab_internet_bank_fund' => array(array('nid' => 15,'title' => '银行理财'), array('nid' => 16,'title' => '基金理财')),
        'panel_internet_insurance' => array(array('nid' => 66,'title' => '保险理财')),
        'panel_school_insurance' => array(array('nid' => 21,'title' => '保险学堂')),
        'panel_school_metal' => array(array('nid' => 24,'title' => '贵金属学堂')),
        'panel_school_gold' => array(array('nid' => 25,'title' => '黄金学堂')),
        'navTab_trade_basic_tech' => array(array('nid' => 26,'title' => '基本面分析'), array('nid' => 27,'title' => '技术面分析')),
        'panel_trade_master' => array(array('nid' => 28,'title' => '大师攻略')),
        'panel2_wealth_story' => array(array('nid' => 29,'title' => '投资案例')),
        'panel2_wealth_plan' => array(array('nid' => 30,'title' => '理财规划')),
        //'panel2_wealth_product' => array(array('nid' => 31,'title' => '产品评测')),

        'navTab_stockSchool_basic_method' => array(array('nid' => 34,'title' => '基础知识'),array('nid' => 36,'title' => '操盘攻略')),
        'panel_stockSchool_trade' => array(array('nid' => 35,'title' => '交易指南')),
        'panel_fundSchool_basic' => array(array('nid' => 37,'title' => '基金入门')),
        'navTab_fundSchool_open_close' => array(array('nid' => 38,'title' => '开放式基金'),array('nid' => 39,'title' => '封闭式基金')),
        'panel_fundSchool_money' => array(array('nid' => 40,'title' => '货币基金')),
        'panel_fundSchool_trade' => array(array('nid' => 41,'title' => '基金技巧')),
        'panel_forexSchool_basic' => array(array('nid' => 42,'title' => '外汇入门')),
        'panel_forexSchool_trade' => array(array('nid' => 43,'title' => '炒汇技巧')),
        'panel_metalSchool_basic' => array(array('nid' => 56,'title' => '基础知识')),
        'panel_metalSchool_trade' => array(array('nid' => 58,'title' => '投资技巧')),
        'panel_otherSchool_bank' => array(array('nid' => 20,'title' => '银行学堂')),
        'panel_otherSchool_insurance' => array(array('nid' => 21,'title' => '保险学堂')),
        'navTab_otherSchool_spot_futures' => array(array('nid' => 22,'title' => '现货学堂'),array('nid' => 23,'title' => '期货学堂')),
        'panel_otherSchool_gold' => array(array('nid' => 25,'title' => '黄金学堂')),
    ),
    'pageTitle' => array(
		'IndexController-index' => array('首页'),
		'PageController-xtHome' => array('财经学堂'),

		'PageController-xtList' => array(),
		'PageController-xtSingle' => array(),
		'PageController-list' => array(),
		'PageController-single' => array(),
		'PageController-tagList' => array('词典'),
		'PageController-tagSingle' => array('词典'),
		'PageController-search' => array(),

		'StaticController-about' => array('关于我们'),
		'StaticController-contact' => array('联系我们'),
		'StaticController-mianze' => array('免责条款'),
		'StaticController-sitemap' => array('网站地图'),
    ),
    'defaultMetaData' => array(
		'keywords' => '慧学网',
		'description' => '慧学网提供提供最专业最全的理财学习网站，提供投资学堂、财经词典、互联网金融、互联网理财、投资案例、理财故事等服务。',
    ),
    'pageMetaData' => array(
		'IndexController-index' => array('keywords' => '投资，理财，股票，基金，外汇，债券，贵金属，黄金，期货，现货，银行，保险，财经学堂，互联网金融，互联网理财，P2P网贷，投资案例，理财规划', 'description' => ''),
		'PageController-xtHome' => array('keywords' => '投资，理财，财经学堂，股票，基金，外汇，债券，贵金属，黄金，期货，现货，银行，保险', 'description' => '慧学网财经学堂提供最专业最全的投资理财知识，涵盖股票、基金、外汇、债券、贵金属、黄金、期货、现货、银行、保险等投资领域。'),

		'PageController-xtList' => array('keywords' => '财经学堂，投资，理财', 'description' => '慧学网财经学堂提供最专业最全的投资理财知识，涵盖股票、基金、外汇、债券、贵金属、黄金、期货、现货、银行、保险等投资领域。'),
		'PageController-xtSingle' => array('keywords' => '财经学堂，投资，理财', 'description' => ''),
		'PageController-list' => array('keywords' => '投资，理财', 'description' => ''),
		'PageController-single' => array('keywords' => '投资，理财', 'description' => ''),
		'PageController-tagList' => array('keywords' => '词典，投资，理财', 'description' => '慧学网财经词典提供最专业最全的理财词汇的中英文学习，涵盖股票、基金、外汇、债券、贵金属、黄金、期货、现货、银行、保险等投资领域。'),
		'PageController-tagSingle' => array('keywords' => '词典，投资，理财', 'description' => ''),
		'PageController-search' => array('keywords' => '搜索，投资，理财', 'description' => ''),

		'StaticController-about' => array('keywords' => '关于我们，投资，理财', 'description' => ''),
		'StaticController-contact' => array('keywords' => '联系我们，投资，理财', 'description' => ''),
		'StaticController-mianze' => array('keywords' => '免责条款，投资，理财', 'description' => ''),
		'StaticController-sitemap' => array('keywords' => '网站地图，投资，理财', 'description' => ''),
    ),
    'hotNids' => array(6864,6867,6884,6886,6888,6903),
));
